language: php

sudo: false

services:
  - redis-server

env:
    global:
        - COMPOSER_NO_INTERACTION="1"
        - COMPOSER_MEMORY_LIMIT="-1"

matrix:
    include:
      - php: 7.1
        env: COMPOSER_ARGS=""
      - php: 7.2
        env: COMPOSER_ARGS=""
      - php: 7.3
        env: COMPOSER_ARGS="" WITH_CS="true"

      - php: 7.1
        env: COMPOSER_ARGS="--prefer-lowest"
      - php: 7.2
        env: COMPOSER_ARGS="--prefer-lowest"
      - php: 7.3
        env: COMPOSER_ARGS="--prefer-lowest"

cache:
    directories:
      - $HOME/.composer/cache

install:
    - IFS=$'\n'; COMMIT_SCA_FILES=($(git diff --name-only --diff-filter=ACMRTUXB "${TRAVIS_COMMIT_RANGE}")); unset IFS

before_script:
    - phpenv config-rm xdebug.ini || true
    - bash -c "composer update $COMPOSER_ARGS"

script:
    - vendor/bin/phpunit
    - if [[ "$WITH_CS" == "true" ]]; then vendor/bin/php-cs-fixer fix --config=.php_cs -v --dry-run --stop-on-violation --using-cache=no --path-mode=intersection "${COMMIT_SCA_FILES[@]}"; fi
